
package com.venki;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://venki.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCatagories", targetNamespace = "http://venki.com/", className = "com.venki.GetProductCatagories")
    @ResponseWrapper(localName = "getProductCatagoriesResponse", targetNamespace = "http://venki.com/", className = "com.venki.GetProductCatagoriesResponse")
    public List<String> getProductCatagories();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://venki.com/", className = "com.venki.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://venki.com/", className = "com.venki.AddProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://venki.com/", className = "com.venki.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://venki.com/", className = "com.venki.GetProductsResponse")
    public List<String> getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
